---
- name: Install Zabbix-agent
  hosts: all
  become: yes

  tasks:

  - name: Install repo Zabbix
    shell: wget https://repo.zabbix.com/zabbix/6.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.0-4%2Bubuntu22.04_all.deb && dpkg -i zabbix-release_6.0-4+ubuntu22.04_all.deb && apt update

#Замена локальной ip в конф. файде на ip сервера zabbix
  - name: Replacement ipaddr
    shell: sed -i 's/127.0.0.1/167.71.34.3/' /etc/zabbix/zabbix_agentd.conf

  - name: Install Zabbix-agent
    apt: name=zabbix-agent state=latest

  - name: Install repo Zabbix
    shell: systemctl restart zabbix-agent && systemctl enable zabbix-agent 
