---
- name: Install Apache and Upload my web Page
  hosts: all
  become: yes


  vars:
    sourse_file: /etc/ansible//index.html
    destin_file: /var/www/html

  tasks:

  - name: Check and Print Linux ansible_os_family
    debug:
      var: ansible_os_family

  - block:   #========Block for Ubuntu============

       - name: Install Apache Web Server
         apt: name=apache2 state=latest

       - name: Copy MyHomePage to Servers
         copy: src={{ sourse_file }} dest={{ destin_file }} mode=0555
         notify: Restart Apache

       - name: Start WebServer and make it enable on boot
         service: name=apache2 state=started enabled=yes
    when: ansible_os_family == "Debian"


  handlers:
  - name: Restart Apache
    service: name=apache2 state=restarted