---
- name: My Super Playbook
  hosts: all
  become: yes

  vars:
    mytext: "Privet ot Dmitriya"

  tasks:
  - name: Ping test
    ping:

  - name: Unregister Server from Load Balancer
    shell: echo This server {{ inventory_hostname }} was deregistered from our Load Balancer, node name is {{ ansible_nodename }} >> /home/log.txt
    delegate_to: 46.101.126.113


  - name: Create file1
    copy:
      dest: /home/file1.txt
      content: |
        This is FileN1
        On ENGLISH Hello World
        On RUSSIAN {{ mytext }}

    delegate_to: linux3

  - name: Create file2
    copy:
      dest: /home/file2.txt
      content: |
        This is FileN2
        On ENGLISH Hello World
        On Russian {{ mytext }}


  - name: Reboot my servers
    shell: sleep 3 && reboot now
    async: 10
    pool: 0

  - name: Wait till my server will come up online
    wait_for:
      host: "{{ inventory_hostname }}"
      state: started
      delay: 10
      timeout: 40